### ISSUE TITLE
Ventures page + Mini-Ventures page

### ISSUE THREAD

**Issue by Wythemars** [stillfleet/stillfleet.github.io#27]
Very minor, but we say "10–12-page" for length, and most are 12–24-ish. Can we just change "10–12-page" to "short" and call it a day? I've updated the MS.

Note, this language is on both the Ventures and the Mini-Ventures pages.

**Comment by armahillo** [comment]
If you're going to use the MS for content updates, can you please do it in "Suggesting" mode? I can accept the suggestions as they've been integrated. We have too much content there for me to be able to tell what changes are made, and this would also include formatting changes.

**Comment by Wythemars** [comment]
Sure, no prob. That said, I'm writing up the entire change directly into these GitHub issues. I keep up the MS since it's very useful, but you'd signaled to focus on GitHub. Let me know if that's still preferred.

**Comment by armahillo** [comment]
Sure -- putting the change in the GH issue is fine. 

Let me see about creating a github issue template that will have prompts to make sure I get the info I need to do the edit correctly the first time through -- it'll be no process difference, but it will pre-fill the issue description with some text that creates sections for you
