### ISSUE TITLE
Page = 2.1.1.3. The Stillfleet Core Rulebook

### ISSUE THREAD

**Issue by Wythemars** [stillfleet/stillfleet.github.io#33]
Add missing copy at bottom, after everything before the footer: 

[SUBHEADER]
Praise

[BODY]
“**_Stillfleet_ has precisely the sort of sci-fi tone that I like**, in that it’s so soft you could spread it on toast. It’s chock-full of Interesting Weird. There are several kinds of magic sword, the rulebook looks like a prog-rock album cover, and very little presented in the fiction is explainable or explained.”
—Grant Howitt, co-designer of _Spire_ and _Heart: The City Beneath_.

“**_Stillfleet_ strikes a perfect balance that eludes the vast majority of TTRPGS**: the system is quick and easy to pickup, but the setting possesses a thoughtfulness and depth—at the first edition!—that rivals any other game… It’s a super-future spacefaring game on its surface, but it succeeds at helping tell stories of political intrigue, cloak and dagger mystery, large-scale geopolitical conflict, cyberpunk noir, and intimate interpersonal drama. **If there is a bottom to the depth stories it can help tell, I have not seen it!**”
—Mike Rugnetta, _Fun City_ GM and former Idea Channel host.

“**_Stillfleet_ is a triumph** that imagines the far far future and the socio-political inter-workings of staying alive. Makes you think about the way you eat, breathe, and bring about change in your provincial space town, on Spindle, and across the universe. **It was so easy to learn, too.**”
—Jenn de la Vega, Fun City player and food influencer.

**Comment by armahillo** [comment]
When you say "After everything before the footer" what do you mean?

<img width="726" alt="Screen Shot 2024-03-25 at 11 41 56 PM" src="https://github.com/stillfleet/stillfleet.github.io/assets/502363/b4b38468-88b4-407c-90c5-410ef66268e1">

Green or Blue, or Red?

Green & Blue are easy. Red will be complicated.

**Comment by armahillo** [comment]
Also -- this content also exists on https://stillfleet.com/press.html -- is that ok?

**Comment by armahillo** [comment]
Like this?

https://github.com/stillfleet/stillfleet.github.io/assets/502363/0d667b60-8ffd-4c17-8397-119b657b0c6a

**Comment by Wythemars** [comment]
Yeah, I mean, I just noticed that I'd wanted to include some blurbs re the game, but those aren't on the main product page. The press page is a mess, so I'd like to keep this here, too. Perhaps we have the "buy" buttons both before and after praise? The "start playing now" footer is fine where it is, at the bottom. Basically, this is fine; I'm just wondering if we want another buy link, or we think this is good. I don't want blurbs to stop buyers.

**Comment by armahillo** [comment]
@Wythemars:
> Yeah, I mean, I just noticed that I'd wanted to include some blurbs re the game, but those aren't on the main product page. The press page is a mess, so I'd like to keep this here, too. Perhaps we have the "buy" buttons both before and after praise? The "start playing now" footer is fine where it is, at the bottom. Basically, this is fine; I'm just wondering if we want another buy link, or we think this is good. I don't want blurbs to stop buyers.

I would say in general with web copy, the prevailing wisdom is that less is more, and users will spend the vast majority of their time scanning a document (but not reading it) for the content they're looking for. So as long as the content is easy to skip over visually (and I would say it's at least that), it shouldn't significantly get in the way. 

That said -- it might be smarter to introduce the buy links earlier in the page so that the user sees them and then knows to return to them later. 

If you'd like me to make content suggestions based on my experience I can do that; I've mostly been assuming the role of facilitator and letting you decide what you want up there.

Either way -- it's deployed!
