### ISSUE TITLE
Updating Blister Critters CTAs (link text)

### ISSUE THREAD

**Issue by Wythemars** [stillfleet/stillfleet.github.io#38]
<img width="1389" alt="Screenshot 2024-05-28 at 9 05 28 PM" src="https://github.com/stillfleet/stillfleet.github.io/assets/119684043/da95d957-7170-4c23-b14d-2a08a4344a76">
<img width="1389" alt="Screenshot 2024-05-28 at 9 05 42 PM" src="https://github.com/stillfleet/stillfleet.github.io/assets/119684043/48b5458a-3536-4f8a-a6e5-5f15ac5db774">
<img width="1389" alt="Screenshot 2024-05-28 at 9 06 15 PM" src="https://github.com/stillfleet/stillfleet.github.io/assets/119684043/21c534e7-1fd0-45d2-8c02-e2a9a2f8af38">

- [x] On the Blister Critters landing page, please change the CTA from "Live on Kickstarter" to "Order the game" —> link to: https://blister-critters.backerkit.com/hosted_preorders/
- [x] Note, on the Blister Critters landing page, the graphic at bottom also needs to be updated. I'll ping Tony. No action for now.
- [x] On the Blister Critters Quickstart page, please change the CTA from "Back us on Kickstarter" to "Order the game" —> link to: https://blister-critters.backerkit.com/hosted_preorders/
- [x] On the Blister Critters Quickstart page, please add any icon for "Blurb the game" as it's just blank right now. This could be the branded Stillfleet bullet (the alchemical symbol for Sol)? Anything works.
- [x] On the Blister Critters Boxed Set page, please change the CTA from "Back us on Kickstarter" to "Order the game" —> link to: https://blister-critters.backerkit.com/hosted_preorders/

Hopefully, we won't have to redo this again until we actually start fulfillment in the fall!

**Comment by Wythemars** [comment]
Updated the CTA language. @armahillo to update the missing icon. Wythe to ping Tony re the new graphic.

**Comment by Wythemars** [comment]
@armahillo , please switch out the CTA graphic at the bottom of the Blister Critters landing page for this new one:

https://drive.google.com/file/d/1lUIz9Bvfbdq-LTm7w0UWZ1sH4zp0_g1q/view?usp=drive_link

**Comment by armahillo** [comment]
Nice work on the content / link updates! :)
