### ISSUE TITLE
games/stillfleet/rules

### ISSUE THREAD

**Issue by armahillo** [stillfleet/stillfleet.github.io#8]
- [x] two column-ish layout favoring text on the left
- [x] collapse the scores list
- [x] internal links with {S} logo
- [x] "Your voidminer's mind and body..." is crashing and needs breathing room
- ~Use new site-wide two column layout~
- [x] Beating 6 / unfolded dice
- [x] Assigning scores / score demo. 
- [x] Remove last border-bottom in scores
- [x] Use side-by-side product inlays for products
- [x] Ditch "Read more" link and use product link

**Comment by Wythemars** [comment]
Please change asterisks to italics
<img width="1365" alt="Core Rules - italics not asterisks" src="https://github.com/stillfleet/stillfleet.github.io/assets/119684043/6bd1a5ea-5e31-4a59-bc45-66ed0e4dafb6">

Please fix bottom padding of product cards
<img width="1365" alt="Core Rules - product cards too much space at bottom" src="https://github.com/stillfleet/stillfleet.github.io/assets/119684043/08216dc4-a33b-4da1-a9b8-35eeb101a94a">
